### ISSUE TITLE
Extracting sub-images of detected objects 

### ISSUE THREAD

**Issue by obyrnemj** [KQTENQK/MOT-DeepSort-CS#1]
Hi, firstly thanks for sharing this code. Its great.

I noticed a small snag when extracting the sub-images before feeding them into the ReID model, in this section of the code:
https://github.com/KQTENQK/MOT-DeepSort-CS/blob/f59a9274569575e74f467ae02f2e7dbe1356096c/src/MOT.CORE/ReID/ReidScorer.cs#L124-L127               

On L126, I think it should be: `BitmapData bitmapData = bitmap.LockBits(rectangle, ImageLockMode.ReadOnly, bitmap.PixelFormat);`

(And also, L155 would need to change too from `image.UnlockBits(bitmapData);` to `bitmap.UnlockBits(bitmapData);`)

**Comment by KQTENQK** [comment]
Hi, thanks for commenting, you are totally right, fixed that!
